version: '3'
services:
  client:
    build:
      context: ./client
    restart: always
    ports:
      - '3001:3001'
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://localhost:5001/api
      - REACT_APP_AUTH0_DOMAIN=dev-2cf59a31.us.auth0.com
      - REACT_APP_AUTH0_CLIENT_ID=a7AR22dNiwqXYB2RjXGnqg5L2crVzcLz
      - REACT_APP_AUTH0_AUDIENCE=https://catcouture.com
      - REACT_APP_AUTH0_REDIRECT_URI=http://localhost:3001/catcouture

  server:
    build:
      context: ./server
    restart: always
    ports:
      - '5001:5001'
      - '9229:9229'
    depends_on:
      - db

    environment:
      - PGDATABASE=postgres
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=password
      - PGPORT=5432
      - AUTH0_AUDIENCE=https://catcouture.com
      - AUTH0_ISSUER_BASE_URL=https://dev-2cf59a31.us.auth0.co

  db:
    build:
      context: ./db
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  db-volume:
