version: '3.8'
services:
  client:
    build:
      context: ./client
    restart: always
    ports:
      - '3001:3001'
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_AUTH0_DOMAIN=${REACT_APP_AUTH0_DOMAIN}
      - REACT_APP_AUTH0_CLIENT_ID=${REACT_APP_AUTH0_CLIENT_ID}
      - REACT_APP_AUTH0_AUDIENCE=${REACT_APP_AUTH0_AUDIENCE}
      - REACT_APP_AUTH0_REDIRECT_URI=${REACT_APP_AUTH0_REDIRECT_URI}

  server:
    build:
      context: ./server
    restart: always
    ports:
      - '5001:5001'
      - '9229:9229'
    depends_on:
      - db
    environment:
      - PGDATABASE=${PGDATABASE}
      - PGHOST=${PGHOST}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}

  db:
    build:
      context: ./db
    restart: always
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  db-volume:
